#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : azure-keyvault-nspkg
Version  : 1.0.0
Release  : 2
URL      : https://files.pythonhosted.org/packages/ae/5c/76a6fee57b2bf7e01cb3b59cda88debd552920b69042786de6ad76905661/azure-keyvault-nspkg-1.0.0.zip
Source0  : https://files.pythonhosted.org/packages/ae/5c/76a6fee57b2bf7e01cb3b59cda88debd552920b69042786de6ad76905661/azure-keyvault-nspkg-1.0.0.zip
Summary  : Microsoft Azure Key Vault Namespace Package [Internal]
Group    : Development/Tools
License  : MIT
Requires: azure-keyvault-nspkg-python = %{version}-%{release}
Requires: azure-keyvault-nspkg-python3 = %{version}-%{release}
Requires: azure-nspkg
BuildRequires : azure-nspkg
BuildRequires : buildreq-distutils3

%description
This is the Microsoft Azure Key Vault namespace package. It isn't intended to

%package python
Summary: python components for the azure-keyvault-nspkg package.
Group: Default
Requires: azure-keyvault-nspkg-python3 = %{version}-%{release}

%description python
python components for the azure-keyvault-nspkg package.


%package python3
Summary: python3 components for the azure-keyvault-nspkg package.
Group: Default
Requires: python3-core
Provides: pypi(azure_keyvault_nspkg)
Requires: pypi(azure_nspkg)

%description python3
python3 components for the azure-keyvault-nspkg package.


%prep
%setup -q -n azure-keyvault-nspkg-1.0.0
cd %{_builddir}/azure-keyvault-nspkg-1.0.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1607992358
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
